export 'menu_admin.dart';
// Products
export 'product/create_product_screen.dart';
export 'product/update_product_screen.dart';
export 'product/show_products_screen.dart';
// Categories
export 'category/create_category_screen.dart';
export 'category/show_category_screen.dart';
export 'category/update_category_screen.dart';
// menu
export 'menu/navegator_screens.dart';
